# Generated by Django 4.1 on 2023-03-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('email_id', models.CharField(max_length=25)),
                ('mobile_no', models.IntegerField(max_length=10)),
                ('user_type', models.IntegerField(max_length=1)),
            ],
        ),
    ]
