# Generated by Django 4.1 on 2023-04-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('game_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_category_name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameFeatures',
            fields=[
                ('game_feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_feature_name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameModes',
            fields=[
                ('game_mode_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_mode_name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('platform_id', models.AutoField(primary_key=True, serialize=False)),
                ('platform_name', models.CharField(max_length=25, unique=True)),
            ],
        ),
    ]
