# Generated by Django 4.1 on 2023-04-14 15:30

import Administrator.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50, unique=True)),
                ('imagepath', models.ImageField(blank=True, null=True, upload_to=Administrator.models.filepath)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subCategory_id', models.AutoField(primary_key=True, serialize=False)),
                ('subCategory', models.CharField(max_length=50, unique=True)),
                ('imagepath', models.ImageField(blank=True, null=True, upload_to=Administrator.models.filepath)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.category')),
            ],
        ),
    ]
