# Generated by Django 4.1 on 2023-04-18 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSystems',
            fields=[
                ('os_id', models.AutoField(primary_key=True, serialize=False)),
                ('os_name', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OSVersions',
            fields=[
                ('version_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50, unique=True)),
                ('os_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.operatingsystems')),
            ],
        ),
    ]
