# Generated by Django 4.1 on 2023-04-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processors',
            fields=[
                ('processor_id', models.AutoField(primary_key=True, serialize=False)),
                ('processor_name', models.CharField(max_length=50)),
            ],
        ),
    ]
