# Generated by Django 4.1 on 2023-04-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_name', models.CharField(max_length=225)),
                ('offer_description', models.CharField(max_length=220)),
                ('offer_tc', models.CharField(max_length=220)),
            ],
        ),
    ]
