# Generated by Django 4.1 on 2023-04-19 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0002_processors'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCards',
            fields=[
                ('vc_id', models.AutoField(primary_key=True, serialize=False)),
                ('vc_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='processors',
            name='processor_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='VCVersions',
            fields=[
                ('vc_version_id', models.AutoField(primary_key=True, serialize=False)),
                ('vc_cersion_name', models.CharField(max_length=50, unique=True)),
                ('vc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrator.videocards')),
            ],
        ),
    ]
