# Generated by Django 4.1 on 2023-04-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0003_videocards_alter_processors_processor_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vcversions',
            old_name='vc_cersion_name',
            new_name='vc_version_name',
        ),
    ]
